### ISSUE TITLE
Authentication in the production environment

### ISSUE THREAD

**Issue by wenche** [equinor/data-marketplace#125]
We have two URLs available for people to use
- https://web-data-marketplace-prod.radix.equinor.com
- https://data-marketplace.app.radix.equinor.com

The user need to log in to see the application, but this doesn't work properly across browsers and the two URLs.

**To Reproduce**
Go to one of the urls, preferably (`web-data-marketplace`)

It seems like if it works more often with FF than Chrome

**Expected behavior**
A logged in view of the application

**Screenshots**
![Skjermbilde 2022-08-10 kl  08 40 21](https://user-images.githubusercontent.com/1568252/183832660-69821875-ed69-4834-b042-d1e5e589d8af.png)

**Desktop (please complete the following information):**
 - OS: Mainly affects Chrome. Often works in FF. Haven't tested with Edge or Safari yet

**Smartphone (please complete the following information):**

**Additional context**
Logs from [Radix](https://console.radix.equinor.com/applications/data-marketplace)
```
GET request to https://equinor-dev.collibra.com/rest/2.0/navigation/most_viewed failed: 401 ()
[PopularAssetsHandler] HttpError: Request failed with status code 401
    at Function.request (/opt/app/.next/server/chunks/827.js:83:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getPopularAssets (/opt/app/.next/server/pages/api/popular.js:41:29)
    at async PopularAssetsHandler (/opt/app/.next/server/pages/api/popular.js:77:30)
    at async Object.apiResolver (/opt/app/node_modules/next/dist/server/api-utils/node.js:179:9)
    at async NextNodeServer.runApi (/opt/app/node_modules/next/dist/server/next-server.js:381:9)
    at async Object.fn (/opt/app/node_modules/next/dist/server/base-server.js:500:37)
    at async Router.execute (/opt/app/node_modules/next/dist/server/router.js:213:36)
    at async NextNodeServer.run (/opt/app/node_modules/next/dist/server/base-server.js:619:29) {
  body: {
    statusCode: 401,
    titleMessage: 'Unauthorized',
    helpMessage: 'Please check the application logs for more information.',
    userMessage: 'The bearer token is expired',
    errorCode: 'expiredToken'
  },
  headers: {
    date: 'Wed, 10 Aug 2022 06:35:41 GMT',
    'content-type': 'application/json;charset=ISO-8859-1',
    'content-length': '191',
    connection: 'close',
    'set-cookie': [
      'AWSALBTG=KZ9MNZBHnznrruE+Mpe9UTjkSrVi6yPToeV//gPJCR0R6C9fmXN0RozzYw8P4cNgBsNRxuxPJIz3iLOTY25GneKoWWjTgMkge3IltSCM/yE6mtwPfA7R8WH0ggGwv7rQfsNTZRLmslTXVyoGhjl+5qz7yftTe4GBYrwYE2AFHeFBD9G2ZBc=; Expires=Wed, 17 Aug 2022 06:35:41 GMT; Path=/',
      'AWSALBTGCORS=KZ9MNZBHnznrruE+Mpe9UTjkSrVi6yPToeV//gPJCR0R6C9fmXN0RozzYw8P4cNgBsNRxuxPJIz3iLOTY25GneKoWWjTgMkge3IltSCM/yE6mtwPfA7R8WH0ggGwv7rQfsNTZRLmslTXVyoGhjl+5qz7yftTe4GBYrwYE2AFHeFBD9G2ZBc=; Expires=Wed, 17 Aug 2022 06:35:41 GMT; Path=/; SameSite=None; Secure',
      'rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Tue, 09-Aug-2022 06:35:41 GMT; SameSite=lax'
    ],
    server: 'Apache',
    'strict-transport-security': 'max-age=63072000; includeSubdomains;, max-age=63072000; includeSubDomains;',
    'x-frame-options': 'DENY',
    'referrer-policy': 'no-referrer-when-downgrade',
    'x-content-type-options': 'nosniff',
    'content-security-policy': "default-src 'none'; frame-ancestors 'none'",
    'x-xss-protection': '1; mode=block',
    'www-authenticate': 'Bearer realm="application"'
  },
  statusCode: 401,
  statusMessage: 'Unauthorized'
}
```

**Comment by nilsml** [comment]
Let's see if changing the auth process will fix this
